

library(BiocManager)
options(repos = BiocManager::repositories())

library(shiny)
#library(dropClust)
library(ggplot2)
library(Seurat)
library(shinythemes)
library(TissueEnrich)
library(SummarizedExperiment)
library(SingleCellExperiment)
library(igraph)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(org.Hs.eg.db)
library(karyoploteR)
library(shinyalert)
library(dorothea)
library(textshape)
library(tidyr)
library(tidyverse)
library(reshape2)
library(data.table)
library(networkD3)
library(ggplot2)
library(shinyFiles)
library(dorothea)
library(bcellViper)
library(dplyr)
library(viper)
library(cli)
library(rtracklayer)
data_1<-list()
return_list<-list()
DE_list = list()
DE_up=list()
RES<-list()
library(shiny)
library(Seurat)
library(dropClust)

library(shinythemes)
library(shinycustomloader)
library(shinyjs)
library(igraph)
library(shinybusy)
library(XVector)
library(shinyWidgets)
library(shinyalert)
library(shinyFiles)
library(memisc)
library(AUCell)
library(dorothea)
library(networkD3)
library(bcellViper)
library(dplyr)
library(viper)
#library(Rcpp)
#library(RcppEigen)

# library(utils)
library(ggplot2)
###dependencies
#library(plotly)
#library(impute)
library(data.table)
#library(dqshiny)
#library(GGally)
#library(RobustRankAggreg)
library(shinythemes)
library(shinyBS)
library(DESeq2)
library(MAST)
# Rcpp::sourceCpp("src/util.cpp")
abc <- readRDS("R/abc.rds")
xyz <- readRDS("R/xyz.rds")
pqr <- readRDS("R/pqr.rds")
gensets <- readRDS("R/gensets.rds")
gse<-readRDS("R/gse.RDS")
doro<-readRDS("R/dorothea_regulon_human.RDS")
meta<-readRDS("R/meta.RDS")