// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// ColDispersion_sp
Eigen::VectorXd ColDispersion_sp(Eigen::SparseMatrix<double> mat);
RcppExport SEXP _dropClustOnline_ColDispersion_sp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(ColDispersion_sp(mat));
    return rcpp_result_gen;
END_RCPP
}
// ColDispersion_dense
Eigen::VectorXd ColDispersion_dense(Eigen::MatrixXd mat);
RcppExport SEXP _dropClustOnline_ColDispersion_dense(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(ColDispersion_dense(mat));
    return rcpp_result_gen;
END_RCPP
}
// ColDispersion
Eigen::VectorXd ColDispersion(SEXP mat);
RcppExport SEXP _dropClustOnline_ColDispersion(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(ColDispersion(mat));
    return rcpp_result_gen;
END_RCPP
}
// reduce_genes_cpp
RcppExport SEXP reduce_genes_cpp(List& l);
RcppExport SEXP _dropClustOnline_reduce_genes_cpp(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_genes_cpp(l));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dropClustOnline_ColDispersion_sp", (DL_FUNC) &_dropClustOnline_ColDispersion_sp, 1},
    {"_dropClustOnline_ColDispersion_dense", (DL_FUNC) &_dropClustOnline_ColDispersion_dense, 1},
    {"_dropClustOnline_ColDispersion", (DL_FUNC) &_dropClustOnline_ColDispersion, 1},
    {"_dropClustOnline_reduce_genes_cpp", (DL_FUNC) &_dropClustOnline_reduce_genes_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dropClustOnline(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
