# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ColDispersion <- function(mat) {
    .Call(`_dropClustOnline_ColDispersion`, mat)
}

reduce_genes_cpp <- function(l) {
    .Call(`_dropClustOnline_reduce_genes_cpp`, l)
}
